theme: jekyll-theme-cayman
encoding: UTF-8
title: Welcome to my homepage!
description: Bookmark this to keep an eye on my project updates
#twitter_username: me
github_username:  nbstrat

#repository: nbstrat/GenericEventHandlerSample
